### ISSUE TITLE
Skybox video on homepage

### ISSUE THREAD

**Issue by davexoxide** [Lullabot/vr.lullabot.com#1]
Use video from retreat, stored in dropbox

**Comment by sirkitree** [comment]
The folder is empty. I emailed @jjeff to see if he still has those files.

**Comment by sirkitree** [comment]
Here's the video I think we could use: https://www.dropbox.com/s/tl8sqvpxxejwigx/Video%20Feb%2001%2C%201%2040%2002%20PM.mp4?dl=0
