### ISSUE TITLE
[Team photo] experience

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/vr.lullabot.com#6]
I have a start on this here: https://github.com/Lullabot/vr.lullabot.com/tree/gh-pages/team-photo

The idea is to 
* have one of these hover entities on each person's face (take some time to get coordinates right)
* make each hover entity face the user at all times
* devine a way to have each person's name (and possibly title) show on hover

**Comment by sirkitree** [comment]
@davexoxide I took your latest work and reworked it just a little bit.

I saw the problems you were having with the labels getting overlapped by the hovers, and setting the hovers to invisible negates their ability to have the mouseenter/leave components work.

So the best way to handle this was by using javascript instead to hide and show everything at certain times. The logic is basically this:

```
      // when you mouse over nothing
      //   all hovers are visible
      //   all labels are invisible
      // when you mouse over a hover
      //   one label is visible
      //   all other labels are invisible
      //   all other hovers are invisible
```

Take a look at the updated [live code](https://github.com/Lullabot/vr.lullabot.com/blob/gh-pages/team-photo/index.html) and you can see the javascript I added at the bottom.

There is still some work to do here, but I think we have the hard part figured out. Now we just need to get our hover geometry in place and add the appropriate variables.

Things to remember:
* each hover should have a unique id starting with `hover-`
* each image should have a unique id starting with `label-`
* each hover should also have a target attribute that is the corresponding label
* the hover and the label then need added to the script for selection
* they also need added to the hover and label arrays

One that is done for each one, then we should have this wrapped up.

@wesruv I think this is something you can work on as well.

**Comment by davexoxide** [comment]
@sirkitree excellent approach and that was feeling like the blocker for me. Thanks for the push forward.

**Comment by wesruv** [comment]
http://lullabot.github.io/vr.lullabot.com/team-photo/

Going to mark this done.
