### ISSUE TITLE
[dvr] feedback

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/vr.lullabot.com#8]
- [x] redirect vr.lullabot.com to the experience (i know we talked about this one, sorry to repeat)
- [x] agreed with removing the ‘got it’ click screen and interaction (some of them had issues finding it, and were looking at a blue screen)
- [x] thought that it was too hard to find the easter eggs, and wanted a consistent pattern to follow once you’ve found one. so i ask: would it be too much trouble to move the hover state hit-boxes to the same place, like always using the person’s nose? 
- [ ] said that having more easter eggs would be nice if we had more time, maybe starting with the people that will be at the drupalcon booth (haley has a list if we want it). specifically, could we add something in the center of the hands at the bottom? i know this is a weird limbo space right at the bottom/center of the image, so they said theyd leave that one up to us, but it was suggested to show party info (or just a floppy disk image) near our fingers

**Comment by sirkitree** [comment]
> agreed with removing the ‘got it’ click screen and interaction (some of them had issues finding it, and were looking at a blue screen)

instead of removing this one, i've duplicated this and placed it below, so that when you look down, or if your phone is downward when you load it up, you still see the message before it moves to the next screen.

**Comment by sirkitree** [comment]
> thought that it was too hard to find the easter eggs, and wanted a consistent pattern to follow once you’ve found one. so i ask: would it be too much trouble to move the hover state hit-boxes to the same place, like always using the person’s nose?

for this one, I think that what I'd like to do is just change the easter eggs to a click. so if you hover, you see the regular overlay with the person's name, but only if you click will you see the easter egg.

**Comment by davexoxide** [comment]
The clicking action also has an added bonus of not letting the screen go to sleep so quickly.

**Comment by marstoyship** [comment]
First of all, thanks for recording this and tracking progress! 

I just went to vr.lullabot.com/dvr and it skipped the explanation of how to use the cardboard completely...is this just a hiccup? I was hoping to preview the update related to this comment:
>  i've duplicated this and placed it below, so that when you look down, or if your phone is downward when you load it up, you still see the message before it moves to the next screen.


Also, I'm playing around with the click interaction...is the intention to be able to click again to turn the easter egg off? Jeff's turns off, but mine doesn't. 

Going to loop in the marketing group for any additional clarification/feedback on new updates: @mettamatt @sethlbrown @jponch @bskowron @haleyelizabeth

**Comment by sirkitree** [comment]
HA! Oops, yeah it was getting late, my mistake. I'll fix that soon. I basically removed it cuz refreshing the whole thing as i develop, waiting for the timer, clicking through was becoming tedious and I accidentally committed that.

**Comment by sirkitree** [comment]
ok should be better now @marstoyship

**Comment by marstoyship** [comment]
Ohhh, that makes total sense now. Thanks!

**Comment by marstoyship** [comment]
Honestly, reviewing this again after the loading screens have been added back in, I am confused. I really preferred the original changes we'd recommended in the list above, specifically 1. remove the second loading screen with the 'got it' clock prompt, and 2. adjust the hover states to appear from the same places (like each persons' nose, and not use a click). I think we are creating an unnecessary barrier into the experience, and potentially drastically reducing the amount that people will discover the easter eggs. Just wanted to share from an experience perspective.

**Comment by sirkitree** [comment]
I'm fine with removing the second loading screen. I think that is a fine adjustment and one we can easily make.

The clicking for easter eggs serves a couple purposes though, which I think we should keep.
1. it makes so the screen stays on. there's a thing where your screen goes to sleep that the current version of aframe we're using does not account for. clicking keeps this at bay.
1. easter eggs are not supposed to be easy to find.
1. by clicking to show an easter egg, we keep them on the screen. this means that if someone finds one, they will start clicking on everybody to see if they can find another. I think it's a good addition to the experience.

**Comment by mettamatt** [comment]
If the user needs to click to show an easter egg, the "hit area" should
probably be really big... like the whole person.

**Comment by marstoyship** [comment]
Hmm, ok, good to know. Thanks for the feedback. I think the screen staying on is a good advantage. DO you know how long it takes for it to fall asleep, generally? I think people will be in the experience for a fairly short amount of time, but if it's longer than the screen takes to dim, it makes sense. 

Then I have to ask...should we be leaving in the second blue screen, if we are trying to teach people that they can click for easter eggs? Or is that more of a hint than we want to give?

**Comment by sirkitree** [comment]
>  redirect vr.lullabot.com to the experience (i know we talked about this one, sorry to repeat)

instead of a redirect, I actually moved it here and updated the paths. the old index can be found in `/spin`

**Comment by mettamatt** [comment]
I had a chance to try out the VR experience today. It's great. A couple observations, none of which are deal breakers. 

- The first screen i saw was the "Tap VR icon" screen. Because of the alignment (see screenshot), it wasn't full clear which icon was the VR icon. I think adjusting the horizontal alignment of the icons would have made it more clear to me. Or even: Step 1: Tap VR icon. Step 2. Insert phone into Cardboard. 

![img_7605](https://cloud.githubusercontent.com/assets/321285/15049567/ec33650a-12bc-11e6-8cc2-c5c896fc49cc.PNG)

- The following grey screen about rotating the phone into the cardboard is very helpful!

- I like clicking the easter eggs. Looks like the person's face is the "hit area" for the easter egg. Can you click to turn them off again? I had an issue where Wes's easter egg (his name?) was covering up another person's face and I couldn't make Wes' name disappear. 

- The floppy disk is awesome.

**Comment by bskowron** [comment]
Yeah I just took this for a spin too, and I really like the recent changes. I agree with Matt's feedback, but otherwise I feel like this is just about good to call done!

**Comment by sirkitree** [comment]
> Can you click to turn them off again?

Currently you can, but you have to click the actual easter egg element. So if you had clicked on the label that was covering another person's face, it would have disappeared. I think we could put logic in to click the same hotspot to turn it off which would be a good addition.
